# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'OCRTEST' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for OCRTEST
    pod 'TesseractOCRiOS', '~> 4.0.0'

  target 'OCRTESTTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'OCRTESTUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end